### ISSUE TITLE
AC-FPN code

### ISSUE THREAD

**Issue by Mozen** [Caojunxu/AC-FPN#1]
Thank you very much for your open source. but I can't find where the AC-FPN code， could you tell me some detail？

**Comment by lxtGH** [comment]
It is in FPN file. https://github.com/Caojunxu/AC-FPN/blob/master/detectron/modeling/FPN.py

**Comment by wqfeng1088** [comment]
> It is in FPN file. https://github.com/Caojunxu/AC-FPN/blob/master/detectron/modeling/FPN.py

Thank you very much for your open source. but I can't find where the CxAM and CnAM code， could you tell me some detail？

**Comment by jiawenhao2015** [comment]
Thank you very much for your open source. but I can't find where the CxAM and CnAM code， could you tell me some detail？

**Comment by sunpeng1996** [comment]
I can't find where the CxAM and CnAM,too. In fact, I can't find where is the AC-FPN, Could you show me the code? @jiawenhao2015 @wqfeng1088

**Comment by jiawenhao2015** [comment]
> I can't find where the CxAM and CnAM,too. In fact, I can't find where is the AC-FPN, Could you show me the code? @jiawenhao2015 @wqfeng1088

can't find neither

**Comment by Caojunxu** [comment]
Thank you for your attention, we just release the code of CEM right now, it has boosted the performance almost 3% AP in FPN(resnet50) already, hope it helps you. 
Thanks again for getting your attention.

**Comment by caobin2019-cmd** [comment]
> Thank you for your attention, we just release the code of CEM right now, it has boosted the performance almost 3% AP in FPN(resnet50) already, hope it helps you.
> Thanks again for getting your attention.
you mean that just the CEM module has  boosted the performance almost 3% AP in FPN(resnet50)  without using CxAM and CnAM module
