### ISSUE TITLE
 can AC-FPN be used in a one-stage object detection network？

### ISSUE THREAD

**Issue by 924175302** [Caojunxu/AC-FPN#4]
Hello, I would like to ask, can AC-FPN be used in a single-stage target detection network? For example, YOLO V4. If yes, what needs to be modified? Hope you can answer, thank you！

**Comment by Caojunxu** [comment]
Yes, you just need to modify the fpn, for example, put the CEM on last output of the backbone.

**Comment by Alex-afka** [comment]
> Yes, you just need to modify the fpn, for example, put the CEM on last output of the backbone.

just CEM in fpn？ not use AM？

**Comment by Caojunxu** [comment]
@Alex-afka You can use both
