### ISSUE TITLE
CEM implementation

### ISSUE THREAD

**Issue by NoviceCrom** [Caojunxu/AC-FPN#5]
Can not find CEM part in detectron/modeling/FPN.py, could you point out where it is?

**Comment by Caojunxu** [comment]
Here https://github.com/Caojunxu/AC-FPN/blob/master/detectron/modeling/FPN.py#L354

**Comment by byfate** [comment]
> Here https://github.com/Caojunxu/AC-FPN/blob/master/detectron/modeling/FPN.py#L354

hi nice work,I am wondering if the detectron implementation use dcn ,the paper mentioned,but i cannot find in fpn.py using dcn，also i cann't find it in the paper's graph too.And I want to ask if the CEM only used in p5?appreciated if you can reply.

**Comment by Caojunxu** [comment]
Duplicate of #8
