### ISSUE TITLE
about deformable convolution and CEM use 

### ISSUE THREAD

**Issue by byfate** [Caojunxu/AC-FPN#8]
hi nice work,I am wondering if the detectron implementation use dcn ,the paper mentioned,but i cannot find in fpn.py using dcn，also i cann't find it in the paper's graph too.And I want to ask if the CEM only used in p5?appreciated if you can reply.

**Comment by Caojunxu** [comment]
![image](https://user-images.githubusercontent.com/10076731/101627849-eb5a5c00-3a59-11eb-89e4-dcb17df4dfb7.png)
Hi byfate, you can use dcn in CEM(box). I didn't implement dcn with detectron, so it would be cool if you can implement it. CEM will pass the information from top to bottom like origin FPN, so each layer of P2~P5 can use it. 
Thank you for your attention.
